### PR TITLE
Add more filters

### PR DESCRIPTION
**Pull request by asinghvi17**
This PR aims to add the following filters, for compatibility with NetCDF4 and HDF5 files:

- [X] Fletcher32
- [X] FixedScaleOffset
- [x] Quantize
- [x] Shuffle
- [x] Delta

It also splits the filters into a new folder and documents the API for people who might want to add new filters.

### CODE REVIEW

**Comment by asinghvi17** [comment]
Everything here more or less works, I still have to test the FixedScaleOffset tests though.

I also want to add this to the Python tests to test the I/O.  What's the best way to do that?

**Comment by asinghvi17** [comment]
This PR is pretty much done from my end - I will continue development and refactoring the compressor/filter stack under a single `Codec` type in a new branch https://github.com/JuliaIO/Zarr.jl/tree/as/codecs which already holds a bit of preliminary/API work.

**Review by meggart — APPROVED** [review]

**Comment by meggart** [comment]
Hey @asinghvi17 another ping. I would really like to start working on the zarrv3 branch again but would ideally merge this one and rebase to minimize conflicts. Also, if you could rebase this PR on current master there would not be unrelated test failures anymore.

**Comment by asinghvi17** [comment]
Sorry, this slipped off my radar for a bit.  Should be done now, and all CI seems green as well.

**Pull request merged**
